### ISSUE TITLE
为啥我更新依赖的版本就会报错呢？

### ISSUE THREAD

**Issue by zxhans** [szkeli/tdesign-vue-nuxt-starter#15]
![image](https://github.com/user-attachments/assets/f08ae10a-a406-439c-a888-27b3b06472b0)

**Comment by AnotiaWang** [comment]
可能是 @nuxt/devtools 的 1.6.0 版本导致的，你试试先不要更新它？
https://github.com/nuxt/devtools/pull/746

**Comment by AnotiaWang** [comment]
`main` 分支推了一个 commit，试试它？
我先做了一遍 `npx nuxi upgrade --force`，然后再升级的依赖

**Comment by zxhans** [comment]
好的，谢谢，我主要是想升级tdesign和nuxt，其他的都还好

**Comment by zxhans** [comment]
已经解决了，更新后就可以了，谢谢！~ 这个项目很好用，感谢作者的指点

**Comment by zxhans** [comment]
WARN  7 deprecated subdependencies found: are-we-there-yet@2.0.0, gauge@3.0.2, glob@7.2.3, glob@8.1.0, inflight@1.0.6, npmlog@5.0.1, rimraf@3.0.2 
直接用你更新的就没问题，一旦我升级一下或者增加一个库，pnpm i 就会报上面的，然后就出错了

> nuxt prepare


[09:13:16]  ERROR  require() of ES Module D:\codeprojects\git-projects\zx-projects\zx-frontend\cloudres\cloudres-search\tdesign-nuxt\node_modules\.pnpm\unplugin-vue-router@0.10.8_rollup@4.24.0_vue-router@4.4.5_vue@3.5.12_typescript@5.6.3___vue@3.5.12_typescript@5.6.3_\node_modules\unplugin-vue-router\dist\chunk-6F4PWJZI.js not supported.
chunk-6F4PWJZI.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename chunk-6F4PWJZI.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in \\?\D:\codeprojects\git-projects\zx-projects\zx-frontend\cloudres\cloudres-search\tdesign-nuxt\node_modules\.pnpm\unplugin-vue-router@0.10.8_rollup@4.24.0_vue-router@4.4.5_vue@3.5.12_typescript@5.6.3___vue@3.5.12_typescript@5.6.3_\node_modules\unplugin-vue-router\package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

  chunk-6F4PWJZI.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
  Instead either rename chunk-6F4PWJZI.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in \\?\node_modules\.pnpm\unplugin-vue-router@0.10.8_rollup@4.24.0_vue-router@4.4.5_vue@3.5.12_typescript@5.6.3___vue@3.5.12_typescript@5.6.3_\node_modules\unplugin-vue-router\package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

  at TracingChannel.traceSync (node:diagnostics_channel:315:14)
  at async loadNuxt (/D:/codeprojects/git-projects/zx-projects/zx-frontend/cloudres/cloudres-search/tdesign-nuxt/node_modules/.pnpm/@nuxt+kit@3.13.2_magicast@0.3.5_rollup@4.24.0/node_modules/@nuxt/kit/dist/index.mjs:2663:37)



[09:13:16]  ERROR  require() of ES Module D:\codeprojects\git-projects\zx-projects\zx-frontend\cloudres\cloudres-search\tdesign-nuxt\node_modules\.pnpm\unplugin-vue-router@0.10.8_rollup@4.24.0_vue-router@4.4.5_vue@3.5.12_typescript@5.6.3___vue@3.5.12_typescript@5.6.3_\node_modules\unplugin-vue-router\dist\chunk-6F4PWJZI.js not supported.
chunk-6F4PWJZI.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename chunk-6F4PWJZI.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in \\?\D:\codeprojects\git-projects\zx-projects\zx-frontend\cloudres\cloudres-search\tdesign-nuxt\node_modules\.pnpm\unplugin-vue-router@0.10.8_rollup@4.24.0_vue-router@4.4.5_vue@3.5.12_typescript@5.6.3___vue@3.5.12_typescript@5.6.3_\node_modules\unplugin-vue-router\package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

愣是没想明白。。。 没办法自己加其他的lib库

**Comment by AnotiaWang** [comment]
方面说下你加的什么库吗，我这里复现不出来
